# Generated by Django 3.0.5 on 2026-03-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram_url',
            field=models.URLField(blank=True),
        ),
    ]
