# Generated by Django 3.0.5 on 2026-04-22 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_telegram_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_repo_id',
            field=models.BigIntegerField(blank=True, help_text='GitHub repository ID for auto-synced projects (optional).', null=True, unique=True),
        ),
    ]
