# Generated by Django 3.0.5 on 2026-04-24 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_github_repo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('data', 'Data Analysis'), ('web', 'Web Development'), ('app', 'App Development'), ('ml', 'Machine Learning'), ('programming', 'Programming'), ('other', 'Other')], max_length=20),
        ),
    ]
