# Generated by Django 4.2.30 on 2026-07-02 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_projectimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Resume', 'verbose_name_plural': 'Resume'},
        ),
    ]
