# Generated by Django 4.2.30 on 2026-07-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_profile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hero_tagline',
            field=models.TextField(blank=True, help_text='Short intro shown under your name in the hero section (leave blank to use the default).'),
        ),
    ]
