# Generated by Django 4.2.30 on 2026-07-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profile_hero_tagline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile / Hero Section', 'verbose_name_plural': 'Profile / Hero Section'},
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, help_text='Link to the source code repository (e.g. GitHub).'),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_url',
            field=models.URLField(blank=True, help_text='Link to the live demo / deployed app. For Power BI projects, paste your published dashboard link here (e.g. app.powerbi.com/view?r=...).'),
        ),
    ]
