# Generated by Django 4.2.30 on 2026-07-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_profile_options_alter_project_github_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='synced_from_github',
            field=models.BooleanField(default=False, help_text='Set automatically for projects created by GitHub sync. Synced projects are updated from GitHub; manually added/edited projects are never overwritten.'),
        ),
    ]
