# Generated by Django 4.2.30 on 2026-07-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_project_synced_from_github'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(help_text='Short description of the service offered.')),
                ('icon', models.CharField(choices=[('chart', 'Chart / Analytics'), ('database', 'Database'), ('globe', 'Web / Globe'), ('brain', 'AI / Brain'), ('file', 'Report / File'), ('cogs', 'Automation / Cogs'), ('code', 'Code'), ('cloud', 'Cloud')], default='chart', max_length=20)),
                ('button_label', models.CharField(default='Discuss', help_text="Label for the action button, e.g. 'Discuss', 'Contact', 'Place Order'.", max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
